### ISSUE TITLE
Descendant and child combinators proposal

### ISSUE THREAD

**Issue by Janther** [styletron/styletron#27] opened 2016-12-08 04:42 UTC
Hi,

I just learned today about `Styletron` today and I haven't checked the code yet, but using an educated guess based on this [blog](https://ryantsao.com/blog/virtual-css-with-styletron) I think I can provide a possible approach, or at least start a conversation, to achieve descendant and child combinators.

Imagine this case
```CSS
.foo {
  height: 100px;
  color: green;
}

// we actually want .foo .bar
.bar {
  font-size: 30px;
}
```
```HTML
<div class="foo">
  <div class="bar">
  </div>
</div>
```

With the current implementation you get:

```CSS
.a { height: 100px; }
.b { color: green; }
.c { font-size: 30px; }
```
```HTML
<div class="a b">
  <div class="c">
  </div>
</div>
```

I propose to achieve this using this approach:

```CSS
.foo {
  height: 100px;
  color: green;
}

.foo .bar {
  font-size: 30px;
}
```
```HTML
<div class="foo">
  <div class="bar">
  </div>
</div>
```

should get compiled into this:

```CSS
.a { height: 100px; }
.b { color: green; }
.uniqueFooHash .c { font-size: 30px; }
```
```HTML
<div class="a b uniqueFooHash">
  <div class="c uniqueBarHash">
  </div>
</div>
```

I'm pretty certain that I missed something here but I hope this can get another point of view to and get this idea moving forward.

**Comment by rtsao** [comment] 2016-12-08 08:10
Yeah, I think that general concept of prepending the selector of atomic classes with some scoped class would work. In a sense I think these could be reusable in the same way like atomic classes with media queries or pseudo selectors are:

```jsx
const atomic = styletron.injectDeclaration({prop: 'color', val: 'red', pseudo: ':hover'});
// returns "a"
// and injects ".a:hover {color: red}" to stylesheet
<div className={atomic}>hover me</div>
```

The problem with supporting pseudo classes and media queries is that they become additional qualifications that factor into determining uniqueness. So it becomes, in a sense, "more difficult" to dedupe these declarations (e.g. `@media (max-width: 400) { .p:hover { color: 'red' }` which is pretty specific) so the value of Styletron and virtual CSS is reduced somewhat. In addition, supporting these increases implementation complexity as well.

That said, the making the tradeoff to support media queries seems pretty obvious:
1. There usually aren't that many media queries used in an application. This means declaration re-use is still pretty likely.
2. Media queries are often needed for full layout, so supporting them is imperative for generating critical CSS and server rendering.

In my eyes, the case for pseudo classes seemed weaker, but adding support wasn't much extra implementation cost, and `:hover` styles tend to be extremely common. Plus other pseudo classes can be useful too. Though a lot of these can be implemented in JS, and are less important for critical CSS, it still seemed worth the trade-off to support.

From just my own personal experience, the primary use case I've found for descendant/child combinators is generally along the lines of this:

```css
.parent:hover .child {
  color: red;
}
```

```html
<div class="parent">
  <span class="child"></span>
</div>
```

I actually ran into this when building my blog (with Styletron) as I wanted to have headings such that that when you hovered over them, a link/anchor icon would appear (like headings in github readmes). It's nice to have this work without JS, but ultimately this kind of behavior can be implemented with JS event listeners that trigger state/props changes. I'd be interested in learning about more use cases for descendant selectors, as my general feeling is that React apps don't really need them most of the time.

This is sort of a long-winded answer, but I'm definitely open to supporting descendent/child combinators. I just think it's a matter of getting the API right and being able to implement them in a way that doesn't make Styletron unnecessarily complex/slower/bloated. This is why I haven't implemented them yet, but I also haven't spent as much time thinking it. I hope to do some more thinking on this, but would be interested in seeing more ideas/proposals in this area.

**Comment by batwicket** [comment] 2016-12-18 21:27
Just an aside, but I've also seen a general sibling combinator used in a responsive menu to change styles i.e.

#toggle:checked ~ ul {
      opacity: 1;
      visibility: visible;
    }

<input type="checkbox" id="toggle">
    <label for="menu-toggle" class="label-toggle"></label>
 </input>
 <ul>
    <a href="#"><li>menu entry</li></a>
 </ul>

I don't know enough at this point to say whether sibling combinators are as useful as the others.. just pointing it out.

**Comment by ivanzusko** [comment] 2016-12-19 17:14
@rtsao is there any possibility to add `:before` to an existing styled component?

For example to add some orange circle infront of the `h1` text:

```
import React from 'react';
import {styled} from 'styletron-react';

const Title = styled('h1', () => ({
    fontSize: '3rem',
    border: 'solid .1rem rebeccapurple',
    backgroundColor: 'salmon',
}))

export default function Johnny() {
    return (
        <Title>1. Johnny Juarez</Title>
    )
}
```

I've try like this (added programatycaly `pseudo:before`):
```
const Pseudo = styled('pseudo:before', () => ({
    position: 'absolute',
    width: '2rem',
    height: '2rem',
    left: '0',
    top: '0',
    backgroundColor: 'red',
    content: '""',
    borderRadius: "50%",
    display: 'block'
}))

const Title = styled('h1', () => ({
    fontSize: '3rem',
    border: 'solid .1rem rebeccapurple',
    backgroundColor: 'salmon',
}))

export default function Johnny() {
    return (
        <Title><Pseudo />1. Johnny Juarez</Title>
    )
}
```
and this works just fine, but the main question is there any chance to add some pseudo (doesn't mater `:before`, `:hover` etc.) in another way?

Thanks a lot in advance!

**Comment by ivanzusko** [comment] 2016-12-19 17:19
@rtsao or I need to open separate issue for my question? Sorry.... just first time doing this.

p.s. Thank you for such an exciting tool!

**Comment by javivelasco** [comment] 2017-02-03 09:16
@rtsao An use case for child selector can be a `Button`. Imagine you have a button with arbitrary children and you want to style those cases where one child is an SVG. Should be able, in React, to just write:

```jsx
const styles = props => ({
   '> svg' {
      fill: currentColor,
   },
});
```

It is not possible with the current implementation and that's an important limitation.

**Comment by faddee** [comment] 2017-02-09 12:16
In my opinion as a developer, **not** supporting this, is the beauty of CSS-in-JS and is one of the the strongest arguments of leaving traditional CSS for larger projects. That you won't be surprised by styling from other components or have to deal with specificity. Instead of adopting this towards transitional CSS, we should adopt our self and embrace new ways to solve our problems. The way I solve things like `.my-element > *` is by doing: `<div>{React.Children.map(props.children, child => <Child>{child}</Child>)}</div>`. It doesn't solve everything, but it's a simple example of one way to solve some cases.

**Comment by javivelasco** [comment] 2017-02-09 20:13
@faddee As a user it's ok. As a UI Component lib author it's fucked because, again, there are scenarios where you need to target and style a child. An icon for a `Button` is the perfect example.

**Comment by rtsao** [comment] 2017-02-09 20:21
Yeah, there's definitely valid use cases for descendant combinators if you want to avoid using JavaScript to do something to keep the code lightweight. I think in these cases something along the lines of https://github.com/zeit/styled-jsx is best because you avoid abstraction over CSS entirely, and you just write what you need directly (but avoid polluting the global scope).

**Comment by javivelasco** [comment] 2017-02-09 20:58
@rtsao In my opinion the best about CSS-in-JS is the ability to move the abstraction layer down to properties instead of focusing on classnames. I've worked a lot with CSS Modules and one of the issues I always had is that you need to combine classnames depending on properties for an specific component. This way you are implementing in CSS logic that can be easily resolved in JS, same as in traditional CSS. 

For example, imagine you have a `Button` with `primary` and `raised` props that make the component look with an specific background. In CSS you may want to add a classname for `primary` and another one for `raised` so the *combination* `&.raised.primary {}` assigns the color and that's determined *in the CSS*.  I don't like [styled-jsx](https://github.com/zeit/styled-jsx) too much exactly because of the same thing. To get dynamic styles you have to rely on classnames that that's almost the same as using CSS Modules but with colocation.

I'm porting [react-toolbox](www.react-toolbox.com) to an implementation that allows to use component as factories where you can inject styled primitives. See an example [here](https://twitter.com/javivelasco/status/829770165847986176) using Styled Components, CSS Modules and Fela. I first implemented the Ripple component with all of those plus Styletron and Styled JSX, you can see it [here])(https://twitter.com/javivelasco/status/825048471480696833). But... Styled JSX gave almost no advantages over CSS Modules for my case and Styletron didn't have child selectors so I can't do stuff like targeting children of a Button.

The need of styling a child for an specific component does not pollute the global scope... and I think the need of styling a child has nothing to do with the abstraction. Styletron is great and I wanted to use it for my implementation with demo purposes. It can be ported easily anyway... the only caveat is the lack descendant selectors. :)

**Comment by faddee** [comment] 2017-02-09 21:09
@javivelasco Yes, I understand. But so called "users" will use it if it's available because they are lazy! At least call it `dangerouslyInjectDescendantDeclaration` :-)

**Comment by rtsao** [comment] 2017-02-09 21:16
I think I'd advocate for using two paradigms.

For 90%+ of your UI, you write it with a high-level, component-driven abstraction like styletron-react that supports a subset of CSS. With this you get great performance out of the box with a simple mental model and a non-leaky abstraction.

CSS is a crazy language with support for tons of crazy stuff, all with potentially valid use cases. For these (probably uncommon corner cases where you want to use some CSS rather than using JavaScript), I think it's best to use shadow DOM or something as close to it as possible (e.g. styled-jsx) that mitigates global CSS pollution, but doesn't attempt to provide an abstraction on top of CSS (which will probably be leaky).

My personal opinion is that having two paradigms is better than bringing extra complexity into the first abstraction for the most common use cases.

**Comment by Janther** [comment] 2017-02-09 22:28
I still believe that ditching this CSS feature is not the way to go.

But, having said that, until we figure a way for this that doesn't hinder the great progress and achievements that this library made, and also in favor of a nice API and code complexity, this feature should not be a priority for the moment.

I'm happy that people are giving pros and cons for the feature and I thank you all, but I would also love to see ideas and suggestions on how to tackle the issue as I'm very new to CSS-in-JS myself.

As the saying goes, "A goal without a plan is just a wish".

**Comment by jbellsey** [comment] 2017-02-14 21:53
Just another few cents:

I am building not only a component library, but a themable component-library-building tool. Using Styletron. And loving it, btw.

I have found two situations that *seem* to require descendant selectors.

### (1) Hover & focus states

As @rtsao said above, this is easily implemented with a higher-order component (e.g., `hoverable`) which passes down props (e.g., `hovering`) as needed. Boom, done.

### (2) Nested elements

Another example mentioned above is an icon button. You'd like to style the icon differently when it's rendered inside a button.

Being unable to use descendant selectors makes this seem like an extra layer of problem. In fact, I've found that I appreciated the limitation! In this case, I'm forced to write a thin wrapper around my stock Icon component. The special ButtonIcon component has its own styles and takes its own props.

This is a very small amount of additional code, but it forces you to think in terms of *subclassing* rather than *polymorphing*. This is a good thing, as it keeps your components cleaner and more independent.

There are a few mental shifts we need to make when moving from CSS to CSS-in-JS. There are more mental shifts when using Styletron, which forces to move from thinking in *classes* to thinking in *raw styles*. The issue of descendant selectors is just such a mental shift. I've found that bearing the cognitive dissonance has been quite valuable, and encourage both the author and other users to seriously consider that this omission is a feature, not a bug.

**Comment by igl** [comment] 2017-05-04 17:29
I agree with @jbellsey. When i switched to styletron i was really struck when i noticed that creating more individual child components is much better than having nested rules.
But i am still on the fence about implementing hover states in JS.

Not wanting to pass this trivial "state" as property and call render **VS** passing it implicitly while it's guaranteed to be snappy and "just works"

**Comment by mnpenner** [comment] 2017-05-26 15:40
What about first/last/sibling selectors?

We'd have to pass an index into the component where we do the looping so that we can compute its position, but that feels really dirty. You shouldn't have to pass style info in every time you write a loop!

**Comment by aronallen** [comment] 2017-08-08 17:43
I find styletron a quite amazing beast. 

The lack of child combinators is my single greatest gripe with styletron. I know it would have a negative impact on deduping. Still it really beats having to maintain index references, or hover states in JS land for the sole purpose of styling.

I would even love to fund the time needed to implement this.

**Comment by rtsao** [comment] 2018-04-24 02:02
I've put together a new proposal for this: https://github.com/rtsao/styletron/issues/229

For those interested, I've love feedback on the API!

**Comment by rtsao** [comment] 2018-08-30 04:47
Arbitrary rendering engines (and style object shapes) are supported by Styletron so this could be done. But for `styletron-engine-atomic`, I think this is out of scope.

**Closed by rtsao** 2018-08-30 04:47 UTC
Labels: api, css feature request, discussion
